sizeavatar: 80
sizeavatar2: 50
maxname: 50
maxemail: 255
minlength_pw: 6
pageuser: 20
sent_at: 2
maxcontent: 140
picturesize: 5
sizeavatar3: 30
minimum_age: 0
maximum_age: 150
minimum_phone: 10
maximum_phone: 15
pageproduct: 14
num_features_items: 6
num_stars: 10
maxcomment: 200
pagecomment: 20
